name: Air Quality Sensor Blocks

# The identifier prefix is prepended to the path of every block in _sources/
# to form its globally unique ID. The first component should represent your
# organization; subsequent components describe the collection.
identifier-prefix: r1.tutorial.sensors.

imports:
  # The main OGC Blocks register (GeoJSON Feature, etc.)
  - default
  # The SOSA/SSN Observations register, which we will reference in our schema
  - https://opengeospatial.github.io/ogcapi-sosa/build/register.json